- ext/lib/site/assets/styles.styl
- ext/lib/site/barrios/component.js
- ext/lib/site/barrios/styles.styl
- ext/lib/site/carrusel/styles.styl
- ext/lib/site/foros-en-datos/component.js
- ext/lib/site/foros-en-datos/styles.styl
- ext/lib/site/home-multiforum/component.js
- ext/lib/site/static-pages/styles.styl
Corrige botones de barrios.
Luego del PR cerremos esta branch.
> Agrega gráfico en landing.

- ext/lib/site/footer/component.js
- ext/lib/site/topic-layout/topic-article/comments/component.js
- ext/lib/site/topic-layout/topic-article/comments/form/component.js
- ext/lib/site/topic-layout/topic-article/social/component.js
Cambia argumentos por comentarios.
Agrega links footer.
Agrega texto en el share de twitter.
> Cambios de texto

- ext/lib/site/home-forum/component.js
Randomicé la lista de proyectos por barrio usando el método .sort(() => 0.5 - Math.random())
> randomizando lista de proyectos por barrio

- ext/lib/site/topic-layout/topic-article/social/component.js
- ext/lib/site/topic-layout/topic-article/social/styles.styl
Añadí la funcionalidad para copiar el link de cada topic al portapapeles y mostrar un tooltip si la acción fue exitosa.
> copiar URL del topic al portapapeles

- ext/lib/site/home-forum/component.js
- ext/lib/site/home-forum/styles.styl
- ext/lib/site/home-multiforum/component.js
- ext/lib/site/home-multiforum/styles.styl
- ext/lib/site/jump-button/component.js
- ext/lib/site/jump-button/styles.styl
- ext/lib/site/topic-layout/component.js
- ext/lib/site/topic-layout/styles.styl
- ext/lib/site/topic-layout/topic-article/component.js
> scroll-to-top button

- ext/lib/site/banner-foro-vecinal/component.js
- ext/lib/site/banner-foro-vecinal/styles.styl
> oculta video en mobile

- ext/lib/site/foros-en-datos/component.js
- ext/lib/site/proyectos/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/static-pages/pages/datos.js
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/topic-layout/topic-article/component.js
corrige textos varios en issues #62  y #63
> Correcciones textos

- ext/lib/site/header/component.js
- ext/lib/site/header/styles.styl
- ext/lib/site/proyectos/component.js
Agrega color a :hover
Agrega boton ver mas en carrousel proyectos
Agrega box-shadow en nav
> Agrega link proyectos a navbar. Closes #87.

- ext/lib/site/barrios/component.js
- ext/lib/site/barrios/styles.styl
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/thumbs-voto/styles.styl
- ext/lib/site/topic-layout/topic-article/styles.styl
> Botones en orden

- ext/lib/notifier/jobs/welcome-email/template.js
- ext/lib/site/barrios/component.js
- ext/lib/site/header/component.js
- ext/lib/site/header/mobile-menu/component.js
- ext/lib/site/home-forum/component.js
- ext/lib/site/proyectos/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/thumbs-voto/component.js
> Cambia proyectos -> propuestas. Closes #112.

- ext/lib/site/static-pages/pages/reglamento.js
- ext/lib/site/static-pages/styles.styl
Arregla header y footer de la static reglamento.
> Arregla reglamento. Closes #105.

- ext/lib/site/anchor/index.js
- ext/lib/site/home-forum/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/static-pages/pages/datos.js
- ext/lib/site/static-pages/pages/herramientas.js
- ext/lib/site/static-pages/pages/reglamento.js
- ext/lib/site/static-pages/pages/terminos-y-condiciones.js
No logré resolver el issue en sí, pero simplifiqué el código de varias páginas estáticas y el componente Anchor
> simplificacion de codigo

- ext/lib/site/anchor/index.js
- ext/lib/site/topic-layout/component.js
Cambié uno de los condicionales del componente Anchor para setear un offset acorde al pedido del cliente (que el botón redirigiera hacia el título o el contenido del proyecto). Fijate si es la opción más correcta para completar esa funcionalidad.
> fix go-to-top button

- ext/.eslintrc
- ext/lib/api/index.js
- ext/lib/api/propuestas/index.js
- ext/lib/api/propuestas/utils.js
- ext/package.json
Closes https://github.com/DemocraciaEnRed/vicentelopez/issues/182
> [EN PROGRESO] Add base propuestas api

- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/thumbs-voto/component.js
corrige la fecha de la reunión de vicente lopez y el cambio de la palabra 'idea' por 'propuesta' en acerca de.
> Cambios estáticos

- ext/lib/api/propuestas/index.js
- ext/lib/site/formulario-propuesta/campos.json
- ext/lib/site/formulario-propuesta/component.js
- ext/lib/site/home-propuestas/component.js
Agrega botón de propuestas archivadas
> Add Archivadas button

- ext/lib/site/header/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/topic-layout/topic-article-propuesta/component.js
Agrega los siguientes cambios:
- Agrega firma en el comentario del admin.
- Agrega sharer a propuestas
- Actualiza FAQs
- Cambia logo del header en mobile
> Agrega cambios estaticos

- ext/lib/site/header/component.js
- ext/lib/site/header/mobile-menu/component.js
- ext/lib/site/header/user-badge/component.js
- El menú se cierra al hacer tap afuera de él
- El menú se cierra si el user menu esta abierto y viceversa
> Arregla menú superior en mobile

- ext/lib/site/home-propuestas/topic-card/component.js
- ext/lib/site/home-propuestas/topic-card/styles.styl
Cambia color del boton y del icon-like de acuerdo a si el user ya voto el topic o no.
> Arregla boton 'me gusta'

- ext/lib/site/pdfviewer/component.js
- ext/lib/site/pdfviewer/styles.styl
- ext/lib/site/static-pages/pages/datos.js
- ext/lib/site/static-pages/pages/documentos.js
- ext/lib/site/static-pages/styles.styl
- Saca año 2018 de la línea de tiempo
- Corrige textos cuando no hay archivo disponible
- Agrega paginación al PDF viewer
- Cambia estilos del link al visualizador en s/datos
> Mejoras visualizador

- ext/lib/api-v2/topics/index.js
- ext/lib/api/feed/index.js
- ext/lib/api/index.js
- ext/lib/api/topics/utils.js
- ext/lib/site/formulario-propuesta/component.js
- ext/lib/site/home-propuestas/component.js
- ext/lib/site/home-propuestas/styles.styl
- ext/lib/site/home-proyectos/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/static-pages/pages/datos.js
- ext/lib/site/static-pages/styles.styl
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/topic-layout/topic-article-propuesta/social/component.js
ATENCION! Antes de mergear, reemplazar XXX en el texto del header por el numero de propuestas subidas a la fecha.
> Cierra envio de propuestas y cambia texto header. Mergear 31/05

- ext/lib/site/home-propuestas/topic-card/component.js
- ext/lib/site/home-propuestas/topic-card/styles.styl
Arregla #302.
Cambia colores diferenciados para propuestas factibles, y no-factibles e integradas
> Mejora colores para etiqueta "factible"

- ext/bin/migrate-attrs-anio
Si la migracion ya se corrio, no vuelve a ejecutarse.
> Mejora migracion attrs-anio

- ext/lib/site/proyectos/topic-card/component.js
Agrega link a cards para poder hacer click derecho en ellas
> agrega link a cards

- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/thumbs-voto/styles.styl
Cierra #331 con links a herramientas y cambios en el wording.
> actualiza wording y links

- ext/lib/api-v2/topics/index.js
- ext/lib/api/topics/index.js
- ext/lib/site/formulario-propuesta/component.js
- ext/lib/site/formulario-propuesta/styles.styl
- ext/lib/site/home-propuestas/component.js
- ext/lib/site/home-propuestas/styles.styl
- ext/lib/site/home-proyectos/component.js
- ext/lib/site/home-proyectos/filter/component.js
- ext/lib/site/proyectos/component.js
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/topic-layout/topic-article-propuesta/component.js
- ext/lib/site/topic-layout/topic-article-propuesta/styles.styl
Completado todo lo necesario para el inicio de 2019
> Preparando para inicio 2019

- ext/lib/api-v2/topics/index.js
- ext/lib/notifier/index.js
- ext/lib/notifier/jobs/update-project/index.js
- ext/lib/notifier/jobs/update-project/template.js
- ext/lib/notifier/jobs/update-proposal/index.js
- ext/lib/notifier/jobs/update-proposal/template.js
- ext/lib/site/formulario-propuesta/component.js
Implementado lo siguiente:
- DERVL-42 Las etiquetas no pueden ser las categorias ni viceversa
- DERVL-29 Ahora se envia un email al autor en X->Y cambio de estado de su propuesta/proyecto
> 1.7.0-beta

- ext/lib/site/header/proyectos-link.js
- ext/lib/site/home-proyectos/component.js
- ext/lib/site/home-proyectos/filter/component.js
- ext/lib/site/topic-layout/topic-article-propuesta/component.js
- Se oculta filtro de proyectos ganadores, dejando sólo la vista de seguimiento de los proyectos. 
- Se oculta link en propuestas donde se reenviaba a una vista de proyecto no editada por los administradores, hasta nuevo aviso.
> 1.7.update.tyc

- Dockerfile
- dos-override/lib/admin/admin-topics/export-update/component.js
- dos-override/lib/api-v2/topics/csv.js
- ext/lib/api-v2/index.js
- ext/lib/api-v2/topics/xlsx.js
- ext/package-lock.json
- ext/package.json
- En el listado de los topics se puede descargar el listado de los proyectos en formato EXCEL
> Agregada la posibilidad de descargar listado de proyectos en EXCEL

- config/defaults.json
- ext/lib/site/encuentrosProximos/component.js
- ext/lib/site/encuentrosProximos/styles.styl
- ext/lib/site/formulario-propuesta/component.js
- ext/lib/site/header/component.js
- ext/lib/site/header/mobile-menu/component.js
- ext/lib/site/home-multiforum/component.js
- ext/lib/site/home-propuestas/component.js
- ext/lib/site/home-proyectos/component.js
- ext/lib/site/static-pages/pages/acerca-de.js
- ext/lib/site/static-pages/pages/encuentros.js
- ext/lib/site/static-pages/styles.styl
- ext/lib/site/thumbs-voto/component.js
- ext/lib/site/thumbs-voto/styles.styl
> Ready for 2022 launch (2.0)
